version: '3.8'
services:
  booking-service:
    build:
      context: ./BookingService
      dockerfile: ./Dockerfile
    container_name: booking-service
    restart: unless-stopped
    environment:
      EUREKA_URI: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - user-service
      - hotel-service
    networks:
      - internal

  user-service:
    build:
      context: ./UserService
      dockerfile: ./Dockerfile
    environment:
      EUREKA_URI: http://discovery-service:8761/eureka/
    container_name: user-service
    restart: unless-stopped
    depends_on:
      - discovery-service
    networks:
      - internal

  hotel-service:
    build:
      context: ./HotelService
      dockerfile: ./Dockerfile
    environment:
      EUREKA_URI: http://discovery-service:8761/eureka/
    container_name: hotel-service
    restart: unless-stopped
    depends_on:
      - discovery-service
    networks:
      - internal

  discovery-service:
    build:
      context: ./DiscoveryService
      dockerfile: ./Dockerfile
    container_name: discovery-service
    restart: unless-stopped
    networks:
      - internal

  gateway:
    build:
      context: ./Gateway
      dockerfile: ./Dockerfile
    container_name: gateway
    restart: unless-stopped
    environment:
      EUREKA_URI: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    ports:
      - "8080:8080"
    networks:
      - internal


networks:
  internal:

