app:
  jwt:
#    secret: ${JWT_SECRET:your-very-long-base64-encoded-secret-key}  # Use env var in prod!
    secret: "FnDxV8PXJu8ujaFAKzc0EXKwd/54wzYhmx78i85Bg+o="
    expiration-ms: 86400000  # 24 hours
spring:
  application:
    name: user-service

#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/user_db}
#    username: ${SPRING_DATASOURCE_USERNAME:your_user}
#    password: ${SPRING_DATASOURCE_PASSWORD:your_pass}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update  # 'update' / 'create' / 'create-drop'
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  session:
    jdbc:
      initialize-schema: always
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    non-secure-port-enabled: true
